enable static build
It looks gcc is enough, muslc won't reduce size further.

The static loader will fail to load aonther static app (e_type = ET_EXEC):

	wfg /c/eulermaker/elf/src% ./loader-static /mnt/debian/usr/bin/busybox
	open /mnt/debian/usr/bin/busybox
	dyn=0
	error: can't load ELF /mnt/debian/usr/bin/busybox

ELF header e_type values:

	ET_EXEC, 2, Executable file
	ET_DYN,  3, Shared object file

The root cause is mmap failure:

	wfg /c/eulermaker/elf/src% strace ./loader-static /run/current-system/sw/bin/sleep 0.1
	execve("./loader-static", ["./loader-static", "/run/current-system/sw/bin/sleep", "0.1"], 0x7fff39be2950 /* 105 vars */) = 0
	write(2, "open /run/current-system/sw/bin/"..., 38open /run/current-system/sw/bin/sleep
	) = 38
	openat(AT_FDCWD, "/run/current-system/sw/bin/sleep", O_RDONLY) = 3
	read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\2\0>\0\1\0\0\0`\233@\0\0\0\0\0"..., 64) = 64
	lseek(3, 64, SEEK_SET)                  = 64
	read(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0@\0\0\0\0\0@\0@\0\0\0\0\0"..., 728) = 728
	write(2, "dyn=0\n", 6dyn=0
	)                  = 6
	mmap(0x400000, 1359872, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED_NOREPLACE, -1, 0) = -1 EEXIST (File exists)
	write(2, "error: can't load ELF /run/curre"..., 55error: can't load ELF /run/current-system/sw/bin/sleep

due to both loader itself and the app claims to use 0x400000, leading to address conflict:

	 [+] Program Header Table
	     [Nr] Type            Offset     Virtaddr   Physaddr   Filesiz  Memsiz   Flg  Align
	     [ 2] PT_LOAD         0x0        0x400000   0x400000   0x1d2f0  0x1d2f0  R    0x4096

And all nixos apps' e_type = ET_EXEC, so will suffer from this problem.

	wfg /c/eulermaker/elfspirit% ./elfspirit parse -A /bin/sh|head
	 [+] ELF Header
	     e_type:                       2 -> An executable file

However it's not a problem -- both static programs or nixos programs do
not need transparent container, so don't need this loader as wrapper.

Those programs can be directly symlinked to the env.

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>